import PDFDocument from "pdfkit";

type ReportMetadata = {
  eventId: string;
  sourceTool: string;
  priority: string;
  detectedAt: Date;
  generatedAt: Date;
};

const renderMarkdown = (doc: PDFKit.PDFDocument, markdown: string) => {
  const lines = markdown.split("\n");

  for (const rawLine of lines) {
    const line = rawLine.trim();

    if (line.length === 0) {
      doc.moveDown(0.45);
      continue;
    }

    if (line.startsWith("### ")) {
      doc.fillColor("#0F172A").font("Helvetica-Bold").fontSize(13).text(line.slice(4));
      doc.moveDown(0.25);
      continue;
    }

    if (line.startsWith("## ")) {
      doc.moveDown(0.4);
      doc.fillColor("#0B3A66").font("Helvetica-Bold").fontSize(15).text(line.slice(3));
      doc.moveDown(0.2);
      continue;
    }

    if (line.startsWith("# ")) {
      doc.moveDown(0.4);
      doc.fillColor("#0B3A66").font("Helvetica-Bold").fontSize(17).text(line.slice(2));
      doc.moveDown(0.25);
      continue;
    }

    if (line.startsWith("- ")) {
      doc.fillColor("#111827").font("Helvetica").fontSize(11).text(`• ${line.slice(2)}`, {
        indent: 8,
      });
      continue;
    }

    if (/^\d+\.\s/.test(line)) {
      doc.fillColor("#111827").font("Helvetica").fontSize(11).text(line, { indent: 8 });
      continue;
    }

    doc.fillColor("#111827").font("Helvetica").fontSize(11).text(line);
  }
};

export const renderThreatReportPdf = async (
  analysisMarkdown: string,
  metadata: ReportMetadata,
): Promise<Buffer> => {
  const doc = new PDFDocument({
    size: "A4",
    margins: { top: 56, bottom: 56, left: 56, right: 56 },
    info: {
      Title: `Threat Analysis - ${metadata.eventId}`,
      Author: "Watchdog Threat Analysis Agent",
      Subject: `Threat report for ${metadata.sourceTool}`,
      Keywords: "threat-analysis,watchdog,security",
      CreationDate: metadata.generatedAt,
    },
  });

  const chunks: Buffer[] = [];
  const pdfBuffer = new Promise<Buffer>((resolve, reject) => {
    doc.on("data", (chunk) => {
      chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk));
    });
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });

  doc.fillColor("#0B3A66").font("Helvetica-Bold").fontSize(24).text("Threat Analysis Report");
  doc.moveDown(0.25);
  doc.fillColor("#334155").font("Helvetica").fontSize(10).text("Generated by Watchdog");
  doc.moveDown(0.75);

  doc.fillColor("#0F172A").font("Helvetica-Bold").fontSize(12).text("Case Metadata");
  doc.moveDown(0.2);
  doc.fillColor("#111827").font("Helvetica").fontSize(10);
  doc.text(`Event ID: ${metadata.eventId}`);
  doc.text(`Source Tool: ${metadata.sourceTool}`);
  doc.text(`Priority: ${metadata.priority}`);
  doc.text(`Detected At (UTC): ${metadata.detectedAt.toISOString()}`);
  doc.text(`Report Generated At (UTC): ${metadata.generatedAt.toISOString()}`);

  const lineY = doc.y + 10;
  doc
    .moveTo(doc.page.margins.left, lineY)
    .lineTo(doc.page.width - doc.page.margins.right, lineY)
    .lineWidth(1)
    .strokeColor("#CBD5E1")
    .stroke();
  doc.moveDown(1.2);

  renderMarkdown(doc, analysisMarkdown);
  doc.end();

  return pdfBuffer;
};

